version: '3.8'

services:
  scrapers:
    # Use your Pi-hole container as DNS resolver for scraper container (pihole)
    dns:
    #  - 172.17.0.2
      - 1.1.1.1
      - 8.8.8.8
    # Optional: set restart to recreate with the override when using `docker-compose up`
    restart: unless-stopped
